# Generated by Django 3.2.2 on 2021-05-14 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_alter_coviduserdetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviduserdetail',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 0, 52, 8, 645955)),
        ),
        migrations.AddField(
            model_name='coviduserdetail',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='referrer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 0, 52, 8, 645174)),
        ),
        migrations.AddField(
            model_name='referrer',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='referrer',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
