# Generated by Django 3.2.2 on 2021-05-18 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20210515_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviduserdetail',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 23, 54, 8, 849288)),
        ),
        migrations.AlterField(
            model_name='referrer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 23, 54, 8, 848626)),
        ),
    ]
