# Generated by Django 3.2.2 on 2021-05-18 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20210518_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviduserdetail',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 23, 59, 34, 626519)),
        ),
        migrations.AlterField(
            model_name='referrer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 23, 59, 34, 625942)),
        ),
    ]
