# Generated by Django 3.2.2 on 2021-05-18 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_auto_20210518_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coviduserdetail',
            name='created',
        ),
        migrations.RemoveField(
            model_name='coviduserdetail',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='referrer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='referrer',
            name='modified',
        ),
        migrations.AddField(
            model_name='coviduserdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 18, 18, 42, 22, 989714, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coviduserdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='referrer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 18, 18, 42, 25, 227592, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referrer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
