# Generated by Django 3.2.2 on 2021-05-18 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210518_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 23, 59, 34, 624307)),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='state',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 23, 59, 34, 581883)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 23, 59, 34, 624920)),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'name')},
        ),
    ]
